// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { Config, ConfigData, ConfigTableId } from "./tables/Config.sol";
import { Hackathon, HackathonData, HackathonTableId } from "./tables/Hackathon.sol";
import { HackathonPrize, HackathonPrizeData, HackathonPrizeTableId } from "./tables/HackathonPrize.sol";
import { Submission, SubmissionData, SubmissionTableId } from "./tables/Submission.sol";
import { Vote, VoteTableId } from "./tables/Vote.sol";
