// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { Administrator, AdministratorTableId } from "./tables/Administrator.sol";
import { Config, ConfigTableId } from "./tables/Config.sol";
import { Hackathon, HackathonData, HackathonTableId } from "./tables/Hackathon.sol";
import { HackathonPrize, HackathonPrizeData, HackathonPrizeTableId } from "./tables/HackathonPrize.sol";
import { HackathonVoteNft, HackathonVoteNftData, HackathonVoteNftTableId } from "./tables/HackathonVoteNft.sol";
import { Submission, SubmissionData, SubmissionTableId } from "./tables/Submission.sol";
import { Vote, VoteData, VoteTableId } from "./tables/Vote.sol";
