// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IAdministratorSystem {
  function setAdmin(address _newAdmin) external;

  function changeAdmin(address _newAdmin) external;
}
