// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IAdministratorSystem {
  function deleteHackathonByAdmin(bytes32 _hackathonId) external;
}
