// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IConfigSystem {
  function setOwner(address _owner, bool _isActive) external;

  function setPrizeToken(address _prizeToken) external;
}
