// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IHackathonPrizeSystem {
  function createHackathonPrize(address _voteNft, uint256 _voteNftSnapshot) external;

  function depositPrize(bytes32 _hackathonId, uint256 _amount) external;
}
