// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ISubmissionSystem {
  function setVoteToken(address _voteToken) external;

  function submit(
    bytes32 _hackathonId,
    string memory _name,
    string memory _description,
    string memory _uri,
    string memory _imageUri
  ) external;

  function vote(bytes32 _hackathonId, address _submitter) external;

  function continueVote(bytes memory _requestResult, bytes memory _callbackExtraData) external;

  function withdrawPrize(bytes32 _hackathonId) external;
}
