// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ISubmissionSystem {
  function submit(bytes32 _hackathonId, string memory _name, string memory _uri) external;

  function vote(bytes32 _hackathonId, address _submitter) external;

  function withdrawPrize(bytes32 _hackathonId) external;
}
