// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { HackathonData, HackathonVoteNftData, HackathonPrizeData, SubmissionData, VoteData } from "./../Tables.sol";

interface IViewSystem {
  function getMaxHackathonId() external view returns (bytes32);

  function getHackathon(bytes32 _hackathonId) external view returns (HackathonData memory);

  function getHackathonVoteNft(bytes32 _hackathonId) external view returns (HackathonVoteNftData memory);

  function getHackathonPrize(bytes32 _hackathonId) external view returns (HackathonPrizeData memory);

  function getSubmission(bytes32 _hackathonId, address _submitter) external view returns (SubmissionData memory);

  function getVote(bytes32 _hackathonId, address _voter) external view returns (VoteData memory);

  function getAdministrator() external view returns (address);

  function getHackathonSponsor(bytes32 _hackathonId) external view returns (uint256[] memory, address[] memory);
}
