// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { HackathonData, HackathonPrizeData, SubmissionData } from "./../Tables.sol";

interface IViewSystem {
  function getMaxHackathonId() external view returns (bytes32);

  function getHackathon(bytes32 _hackathonId) external view returns (HackathonData memory);

  function getHackathonPrize(bytes32 _hackathonId) external view returns (HackathonPrizeData memory);

  function getSubmission(bytes32 _hackathonId, address _submitter) external view returns (SubmissionData memory);

  function getVote(bytes32 _hackathonId, uint256 _tokenId) external view returns (bool);
}
