// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/interfaces/IBaseWorld.sol";

import { IHackathonPrizeSystem } from "./IHackathonPrizeSystem.sol";
import { IHackathonSystem } from "./IHackathonSystem.sol";
import { IIncrementSystem } from "./IIncrementSystem.sol";
import { ISubmissionSystem } from "./ISubmissionSystem.sol";

/**
 * The IWorld interface includes all systems dynamically added to the World
 * during the deploy process.
 */
interface IWorld is IBaseWorld, IHackathonPrizeSystem, IHackathonSystem, IIncrementSystem, ISubmissionSystem {

}
